import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView, StyleSheet, Text, View } from 'react-native';

import { PrimaryButton } from '@/components/PrimaryButton';
import { AppColors, FontSize, Radius, Spacing } from '@/constants/theme';

export default function OrderConfirmationScreen() {
  const { orderId = 'QB-0000', pickupTime = '12:30 PM' } = useLocalSearchParams<{ orderId?: string; pickupTime?: string }>();
  return <SafeAreaView style={styles.safeArea}><View style={styles.content}><View style={styles.check}><Text style={styles.checkText}>OK</Text></View><Text style={styles.title}>Order confirmed!</Text><Text style={styles.message}>We&apos;re preparing your food now. Pick it up at the main canteen.</Text><View style={styles.card}><Text style={styles.cardLabel}>ORDER NUMBER</Text><Text style={styles.orderId}>{orderId}</Text><Text style={styles.cardLabel}>ESTIMATED PICKUP</Text><Text style={styles.pickup}>{pickupTime}</Text></View><PrimaryButton label="Track my order" onPress={() => router.replace({ pathname: '/order-tracking' as never, params: { orderId } })} /><PrimaryButton label="Back to menu" onPress={() => router.replace('/home' as never)} variant="secondary" /></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: AppColors.background }, content: { flex: 1, justifyContent: 'center', padding: Spacing.four, gap: Spacing.three }, check: { width: 74, height: 74, borderRadius: Radius.pill, backgroundColor: AppColors.success, alignItems: 'center', justifyContent: 'center' }, checkText: { color: '#FFFFFF', fontWeight: '900', fontSize: FontSize.md }, title: { color: AppColors.text, fontWeight: '900', fontSize: FontSize.xl }, message: { color: AppColors.textSecondary, fontSize: FontSize.md, lineHeight: 24 }, card: { backgroundColor: AppColors.text, borderRadius: Radius.md, padding: Spacing.four, gap: Spacing.two, marginVertical: Spacing.three }, cardLabel: { color: '#BEB5AF', fontSize: FontSize.xs, fontWeight: '900', letterSpacing: 1.5 }, orderId: { color: '#FFFFFF', fontSize: FontSize.xl, fontWeight: '900', marginBottom: Spacing.two }, pickup: { color: AppColors.secondary, fontSize: FontSize.lg, fontWeight: '900' } });