import { router } from 'expo-router';
import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

import { PrimaryButton } from '@/components/PrimaryButton';
import { AppColors, FontSize, Radius, Spacing } from '@/constants/theme';
import { Order } from '@/types/order';

const mockOrders: Order[] = [{ id: 'QB-4821', total: 12.75, pickupTime: 'Yesterday', status: 'Ready for Pickup', createdAt: '23 Sep' }, { id: 'QB-3190', total: 9.5, pickupTime: '18 Sep', status: 'Ready for Pickup', createdAt: '18 Sep' }];

export default function ProfileScreen() {
  return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><Text style={styles.back} onPress={() => router.back()}>Back</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>A</Text></View><View><Text style={styles.title}>Alex Student</Text><Text style={styles.muted}>Campus member · Main campus</Text></View></View><Text style={styles.sectionTitle}>Order history</Text>{mockOrders.map((order) => <View key={order.id} style={styles.order}><View><Text style={styles.orderId}>{order.id}</Text><Text style={styles.muted}>{order.createdAt} · {order.pickupTime}</Text></View><Text style={styles.total}>${order.total.toFixed(2)}</Text></View>)}<View style={styles.note}><Text style={styles.noteTitle}>QuickBite member</Text><Text style={styles.muted}>You&apos;re helping keep campus queues moving.</Text></View><PrimaryButton label="Back to menu" onPress={() => router.replace('/home' as never)} /></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: AppColors.background }, content: { padding: Spacing.four, gap: Spacing.three }, back: { color: AppColors.primary, fontWeight: '900', fontSize: FontSize.md, marginBottom: Spacing.three }, profile: { flexDirection: 'row', alignItems: 'center', gap: Spacing.three, marginBottom: Spacing.four }, avatar: { width: 64, height: 64, borderRadius: Radius.pill, backgroundColor: AppColors.secondary, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: AppColors.text, fontSize: FontSize.xl, fontWeight: '900' }, title: { color: AppColors.text, fontSize: FontSize.xl, fontWeight: '900' }, muted: { color: AppColors.textSecondary, fontSize: FontSize.sm, marginTop: 3 }, sectionTitle: { color: AppColors.text, fontSize: FontSize.lg, fontWeight: '900', marginTop: Spacing.three }, order: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: Spacing.three, backgroundColor: AppColors.surface, borderColor: AppColors.border, borderWidth: 1, borderRadius: Radius.md }, orderId: { color: AppColors.text, fontWeight: '900', fontSize: FontSize.md }, total: { color: AppColors.primary, fontWeight: '900', fontSize: FontSize.md }, note: { backgroundColor: AppColors.surfaceMuted, padding: Spacing.three, borderRadius: Radius.md, marginVertical: Spacing.three }, noteTitle: { color: AppColors.text, fontWeight: '900', fontSize: FontSize.md } });